### ISSUE TITLE
[DOCS] Doxygen Support

### ISSUE THREAD

**Issue by resyfer** [eellak/build-recorder#159]
Documentation of the code in the format specified by [Doxygen](https://www.doxygen.nl/manual/)

**Comment by resyfer** [comment]
As I am very interested in contributing to this project, I am going through the code and felt that the documentation was a bit lacking, and I would like to work on issue while I try to understand all of the code.

**Comment by zvr** [comment]
Thanks for this, but I don't think Doxygen-style comments will be of great benefit to this project, due to small size and simplicity.

**Comment by resyfer** [comment]
@zvr Since I'm done with most of it, is it okay for me to continue and finish it? It's mainly just me writing my understanding of the code as I go through the codebase.

**Comment by zvr** [comment]
@resyfer Of course there is no problem with you going over the code and making comments for your own use, but they will not be merged back in this repo.

I will not be able to go through them and review them, but from a quick look at them, please keep in mind that some of the comments are wrong (e.g. referencing SHA-256 instead of SHA-1, talking about hashing file contents instead of the git hash algorithm, etc.).

**Comment by resyfer** [comment]
@zvr Thanks for pointing out my mistakes, especially about the git hash algo (I had updated the name to SHA-1 from SHA256 after realizing my mistake).

And I understand the reasons for not merging documentation.
